-- CreateTable
CREATE TABLE "public"."Monster" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "size" TEXT,
    "type" TEXT,
    "alignment" TEXT,
    "habitat" TEXT,
    "mainHabitat" TEXT,
    "otherHabitat" TEXT,
    "treasure" TEXT,
    "ac" TEXT,
    "hp" TEXT,
    "initiative" TEXT,
    "walk" TEXT,
    "burrow" TEXT,
    "climb" TEXT,
    "fly" TEXT,
    "hover" TEXT,
    "swim" TEXT,
    "strMod" TEXT,
    "intMod" TEXT,
    "dexMod" TEXT,
    "wisMod" TEXT,
    "conMod" TEXT,
    "chaMod" TEXT,
    "strSave" TEXT,
    "intSave" TEXT,
    "dexSave" TEXT,
    "wisSave" TEXT,
    "conSave" TEXT,
    "chaSave" TEXT,
    "proficient" TEXT,
    "expertise" TEXT,
    "vulnerabilities" TEXT,
    "slashing" TEXT,
    "immunitiesConditions" TEXT,
    "immunitiesDamage" TEXT,
    "blindsight" TEXT,
    "darkvision" TEXT,
    "truesight" TEXT,
    "tremorsense" TEXT,
    "passivePerception" TEXT,
    "languages" TEXT,
    "cr" TEXT,
    "XP." TEXT,
    "pb" TEXT,
    "traits" TEXT,
    "legendaryResistanceCount" TEXT,
    "# of Atk" TEXT,
    "atk1Type" TEXT,
    "atk1Mod" TEXT,
    "atk1Range" TEXT,
    "atk1RangeShort" TEXT,
    "atk1Dam" TEXT,
    "atk1DamageType" TEXT,
    "atk2Type" TEXT,
    "atk2Mod" TEXT,
    "atk2Range" TEXT,
    "atk2RangeShort" TEXT,
    "atk2Dam" TEXT,
    "atk2DamageType" TEXT,
    "atk3Type" TEXT,
    "atk3Mod" TEXT,
    "atk3Range" TEXT,
    "atk3RangeShort" TEXT,
    "atk3Dam" TEXT,
    "atk3DamageType" TEXT,
    "atk4Type" TEXT,
    "atk4Mod" TEXT,
    "atk4Range" TEXT,
    "atk4RangeShort" TEXT,
    "atk4Dam" TEXT,
    "atk4DamageType" TEXT,
    "saveDC" TEXT,
    "savingThrow" TEXT,
    "actionNotes" TEXT,
    "ability" TEXT,
    "spellSaveDC" TEXT,
    "spellSavingThrows" TEXT,
    "spellAttack" TEXT,
    "At Will" TEXT,
    "3/Day" TEXT,
    "2/Day" TEXT,
    "1/Day" TEXT,
    "bonusAction" TEXT,
    "reaction" TEXT,
    "amount" TEXT,
    "legendaryActionSaveDC" TEXT,
    "legendaryActionSavingThrow" TEXT,
    "Legendary Actions." TEXT,
    "lair" TEXT,
    "xp" TEXT,
    "Legendary Resistance" TEXT,
    "Legendary Actions" TEXT,
    "lairSaveDC" TEXT,
    "lairSavingThrows" TEXT,
    "other" TEXT,
    "align" TEXT,
    "speeds" TEXT,
    "STR" TEXT,
    "DEX" TEXT,
    "CON" TEXT,
    "INT" TEXT,
    "WIS" TEXT,
    "CHA" TEXT,
    "Sav. Throws" TEXT,
    "skills" TEXT,
    "WRI" TEXT,
    "senses" TEXT,
    "additional" TEXT,
    "font" TEXT,
    "additionalInfo" TEXT,
    "author" TEXT,

    CONSTRAINT "Monster_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Race" (
    "id" SERIAL NOT NULL,
    "race" TEXT NOT NULL,
    "str" TEXT,
    "dex" TEXT,
    "con" TEXT,
    "int" TEXT,
    "wis" TEXT,
    "cha" TEXT,
    "special" TEXT,
    "source" TEXT NOT NULL,
    "notes" TEXT,

    CONSTRAINT "Race_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Spell" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "level" TEXT NOT NULL,
    "school" TEXT NOT NULL,
    "castingTime" TEXT NOT NULL,
    "duration" TEXT NOT NULL,
    "range" TEXT NOT NULL,
    "area" TEXT,
    "attack" TEXT,
    "save" TEXT,
    "damageEffect" TEXT NOT NULL,
    "ritual" TEXT,
    "concentration" TEXT,
    "verbal" TEXT,
    "somatic" TEXT,
    "material" TEXT,
    "material*" TEXT,
    "source" TEXT NOT NULL,
    "details" TEXT NOT NULL,
    "link" TEXT NOT NULL,

    CONSTRAINT "Spell_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Class" (
    "id" SERIAL NOT NULL,
    "class" TEXT NOT NULL,
    "subclass" TEXT NOT NULL,
    "source" TEXT,
    "notes" TEXT,
    "features" TEXT,
    "level" TEXT,
    "description" TEXT,

    CONSTRAINT "Class_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Race_race_key" ON "public"."Race"("race");
